services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/code/data
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: